### ISSUE TITLE
Is this compatible only with expo?

### ISSUE THREAD

**Issue by KamalSilva007** [flyskywhy/react-native-pixi#1]
I created a new react native app using native CLI. When I try to use this library, I got this error. @flyskywhy 

```
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Projects\React-Native\charts_app\node_modules\@flyskywhy\react-native-gcanvas\android\build.gradle' line: 29

* What went wrong:
A problem occurred evaluating project ':flyskywhy_react-native-gcanvas'.
> Project with path ':android:gcanvas_library' could not be found in project ':flyskywhy_react-native-gcanvas'.
```

React native v- 0.71.8

Dependencies Installed
- "@flyskywhy/react-native-browser-polyfill": "^2.0.1",
- "@flyskywhy/react-native-gcanvas": "^6.0.3"
- "pixi-filters": "^5.2.1",
-  "pixi.js": "^7.2.4",

**Comment by flyskywhy** [comment]
It does not depend on expo.

About `Project with path ':android:gcanvas_library' could not be found in project ':flyskywhy_react-native-gcanvas'`, please read `Add below into /android/settings.gradle` in `README.md` of <https://github.com/flyskywhy/react-native-gcanvas>

**Comment by KamalSilva007** [comment]
Thank you!
