### ISSUE TITLE
Working example for version 3.0.0 

### ISSUE THREAD

**Issue by KamalSilva007** [flyskywhy/react-native-pixi#2]
Can you please provide a working example for the latest version. @flyskywhy 
All the previous once are outdated!

**Comment by flyskywhy** [comment]
Why you said <https://github.com/flyskywhy/GCanvasRNExamples/blob/master/app/components/Pixi.js> as described in `READEM.md` is outdated?

**Comment by KamalSilva007** [comment]
It's giving me https://github.com/flyskywhy/react-native-gcanvas/issues/28 this issue. I can't run it on the emulator. Also, it's using metro. (Metro assests)  So I need to install all the packages of metro as well to use it in the native CLI project. Is there any example without these issues?

**Comment by flyskywhy** [comment]
I think use a real Android device to debug is not a problem.

I don't understand the meaning of `install all the packages of metro`, I just had npm install something, but I never had npm install metro-something. What do you mean? Is expo managed project not expo bare project will do some strange things with `metro`?

**Comment by KamalSilva007** [comment]
But if the app crashes one the emulator mean, there is a issue right? 

What I mean by using metro is, we gonna need additional useless packages to do our work. The example using metro assets. But metro asset dependency is not coming as a single dependency. It has several other peer dependencies such as expo-modules-core that is not needed for us. So what I'm trying to say is, need a clear example only using pixi.js

**Comment by flyskywhy** [comment]
The reason why can not support x64 in emulator for now is described in https://github.com/flyskywhy/react-native-gcanvas/issues/28

The reason why I use `expo-asset` to manage sprite pictures in `pixi.js` is: for now I found only `expo-asset` can be used in android and iOS and Web with debug and release. If you can suggest another asset manage module other than `expo-asset`, I can try it in the example.
